python_sources()

pex_binary(
    name="main_362",
    entry_point="main.py",
    environment="gdal-362-environment",
    execution_mode="venv",
)

pex_binary(
    name="main_384",
    entry_point="main.py",
    environment="gdal-384-environment",
    execution_mode="venv",
)
