FROM python:3.12-slim-bookworm AS base

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgdal-dev python3-venv gcc python3-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

FROM base

COPY myapp.src/main_362.pex /app/main.pex
WORKDIR /app
ENTRYPOINT ["/app/main.pex"]
